/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.io.IOException;
import java.net.*;
import java.security.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.*;
import javax.swing.JOptionPane;
import model.Preferencia;
import util.Constantes;
import util.UtilMsj;
import util.UtilSec;

/**
 *
 * @author Ricardo
 */
public class dialogPreferencias extends javax.swing.JDialog {

    private Socket servidor;
    private PrivateKey privK;
    private PublicKey pubK;
    private PublicKey pubKAjena;
    private int id;

    /**
     * Creates new form dialogPreferencias
     *
     * @param parent
     * @param modal
     * @param id
     * @param servidor
     * @param privK
     * @param pubK
     * @param pubKAjena
     */
    public dialogPreferencias(java.awt.Frame parent, boolean modal, int id, Socket servidor, PrivateKey privK, PublicKey pubK, PublicKey pubKAjena) {
        super(parent, modal);
        initComponents();
        this.servidor = servidor;
        this.privK = privK;
        this.pubK = pubK;
        this.pubKAjena = pubKAjena;
        this.id = id;
        RellenarCombobox();
    }

    private void RellenarCombobox() {
        try {
            SealedObject so = UtilSec.encapsularObjeto(pubKAjena, Constantes.INS_PREF);//le mandamos la opcion
            UtilMsj.enviarObject(servidor, so);
            //lo primero será rellenar los comboBox con los datos de la bd
            so = (SealedObject) UtilMsj.recibirObjeto(servidor);//recibe mensaje para ver si ha ido correcto
            ArrayList<String> relacion = (ArrayList<String>) UtilSec.desencriptarObjeto(so, privK);
            so = (SealedObject) UtilMsj.recibirObjeto(servidor);//recibe mensaje para ver si ha ido correcto
            ArrayList<String> tqhijos = (ArrayList<String>) UtilSec.desencriptarObjeto(so, privK);
            so = (SealedObject) UtilMsj.recibirObjeto(servidor);//recibe mensaje para ver si ha ido correcto
            ArrayList<String> interes = (ArrayList<String>) UtilSec.desencriptarObjeto(so, privK);
            for (String string : relacion) {
                cmbbRel.addItem(string);
            }
            for (String intere : interes) {
                cmbbInteres.addItem(intere);
            }
            for (String tqhijo : tqhijos) {
                cmbbhijos.addItem(tqhijo);
            }
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | ClassNotFoundException | IllegalBlockSizeException | BadPaddingException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlprin = new javax.swing.JPanel();
        pnlTit = new javax.swing.JPanel();
        lblTitloh = new javax.swing.JLabel();
        lblArti = new javax.swing.JLabel();
        cmbbRel = new javax.swing.JComboBox<>();
        sliDepor = new javax.swing.JSlider();
        lblRel1 = new javax.swing.JLabel();
        lblDeportivos1 = new javax.swing.JLabel();
        chbArt = new javax.swing.JCheckBox();
        lblPoli = new javax.swing.JLabel();
        sliPoli = new javax.swing.JSlider();
        lblHijos = new javax.swing.JLabel();
        cmbbhijos = new javax.swing.JComboBox<>();
        lblInteres = new javax.swing.JLabel();
        cmbbInteres = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        lblInteres1 = new javax.swing.JLabel();
        cmbbGenero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlprin.setBackground(new java.awt.Color(44, 40, 40));
        pnlprin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        pnlTit.setBackground(new java.awt.Color(59, 44, 133));

        javax.swing.GroupLayout pnlTitLayout = new javax.swing.GroupLayout(pnlTit);
        pnlTit.setLayout(pnlTitLayout);
        pnlTitLayout.setHorizontalGroup(
            pnlTitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        pnlTitLayout.setVerticalGroup(
            pnlTitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        lblTitloh.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitloh.setForeground(new java.awt.Color(255, 255, 255));
        lblTitloh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitloh.setText("PREFERENCIAS");

        lblArti.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblArti.setForeground(new java.awt.Color(133, 207, 203));
        lblArti.setText("Artisticos:");

        sliDepor.setMajorTickSpacing(50);
        sliDepor.setMinorTickSpacing(5);
        sliDepor.setPaintTicks(true);
        sliDepor.setValue(0);

        lblRel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRel1.setForeground(new java.awt.Color(133, 207, 203));
        lblRel1.setText("Relacion:");

        lblDeportivos1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDeportivos1.setForeground(new java.awt.Color(133, 207, 203));
        lblDeportivos1.setText("Deportivos:");

        lblPoli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPoli.setForeground(new java.awt.Color(133, 207, 203));
        lblPoli.setText("Politicos:");

        sliPoli.setMajorTickSpacing(50);
        sliPoli.setMinorTickSpacing(5);
        sliPoli.setPaintTicks(true);
        sliPoli.setValue(0);

        lblHijos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHijos.setForeground(new java.awt.Color(133, 207, 203));
        lblHijos.setText("Hijos:");

        lblInteres.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblInteres.setForeground(new java.awt.Color(133, 207, 203));
        lblInteres.setText("Interes:");

        btnConfirmar.setBackground(new java.awt.Color(59, 44, 133));
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorder(null);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblInteres1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblInteres1.setForeground(new java.awt.Color(133, 207, 203));
        lblInteres1.setText("Genero:");

        cmbbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        javax.swing.GroupLayout pnlprinLayout = new javax.swing.GroupLayout(pnlprin);
        pnlprin.setLayout(pnlprinLayout);
        pnlprinLayout.setHorizontalGroup(
            pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlprinLayout.createSequentialGroup()
                        .addComponent(lblTitloh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlprinLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlprinLayout.createSequentialGroup()
                                    .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHijos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblRel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblArti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDeportivos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(32, 32, 32))
                                .addGroup(pnlprinLayout.createSequentialGroup()
                                    .addComponent(lblInteres1)
                                    .addGap(60, 60, 60)))
                            .addGroup(pnlprinLayout.createSequentialGroup()
                                .addComponent(lblInteres)
                                .addGap(60, 60, 60)))
                        .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbbhijos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sliPoli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbArt)
                            .addComponent(cmbbRel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sliDepor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbbInteres, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlprinLayout.setVerticalGroup(
            pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitloh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbbRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlprinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeportivos1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliDepor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbArt)
                    .addComponent(lblArti, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPoli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliPoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbhijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInteres1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(pnlprinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlprinLayout.createSequentialGroup()
                    .addComponent(pnlTit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 469, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlprin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlprin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            Preferencia pref = new Preferencia(id, cmbbRel.getSelectedItem().toString(), chbArt.isSelected(),
                    sliDepor.getValue(), sliPoli.getValue(), cmbbhijos.getSelectedItem().toString(), cmbbGenero.getSelectedItem().toString(), cmbbInteres.getSelectedItem().toString());
            SealedObject so = UtilSec.encapsularObjeto(pubKAjena, pref);//le mandos la preferencia
            UtilMsj.enviarObject(servidor, so);
            so = (SealedObject) UtilMsj.recibirObjeto(servidor);//recibe mensaje para ver si ha ido correcto
            boolean exist = (Boolean) UtilSec.desencriptarObjeto(so, privK);
            if (!exist) {
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un erro al borrar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException | IllegalBlockSizeException | ClassNotFoundException | BadPaddingException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chbArt;
    private javax.swing.JComboBox<String> cmbbGenero;
    private javax.swing.JComboBox<String> cmbbInteres;
    private javax.swing.JComboBox<String> cmbbRel;
    private javax.swing.JComboBox<String> cmbbhijos;
    private javax.swing.JLabel lblArti;
    private javax.swing.JLabel lblDeportivos1;
    private javax.swing.JLabel lblHijos;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblInteres1;
    private javax.swing.JLabel lblPoli;
    private javax.swing.JLabel lblRel1;
    private javax.swing.JLabel lblTitloh;
    private javax.swing.JPanel pnlTit;
    private javax.swing.JPanel pnlprin;
    private javax.swing.JSlider sliDepor;
    private javax.swing.JSlider sliPoli;
    // End of variables declaration//GEN-END:variables
}
