package frames;

import frames.admin.dialogAdmin;
import java.net.*;
import java.security.*;
import model.User;

/**
 *
 * @author Ricardo
 */
public class frmMain extends javax.swing.JFrame {

    private Socket servidor;
    private PrivateKey privK;
    private PublicKey pubK;
    private PublicKey pubKAjena;
    private User user;

    /**
     * Creates new form frmMain
     */
    public frmMain(Socket servidor, PrivateKey privK, PublicKey pubK, PublicKey pubKAjena, User user) {
        initComponents();
        this.pubKAjena = pubKAjena;
        this.privK = privK;
        this.pubK = pubK;
        this.servidor = servidor;
        this.user = user;
        isAdmin();
    }

    private void isAdmin() {
        if (!user.isAdmin()) {
            mnuAdmin.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mnuPrinci = new javax.swing.JMenuBar();
        mnuAdmin = new javax.swing.JMenu();
        menuItemAdm = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuPerfil = new javax.swing.JMenuItem();
        mnuPref = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 40, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        mnuPrinci.setBackground(new java.awt.Color(59, 44, 133));

        mnuAdmin.setBackground(new java.awt.Color(59, 44, 133));
        mnuAdmin.setText("Administrador");
        mnuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminActionPerformed(evt);
            }
        });

        menuItemAdm.setText("Administar");
        menuItemAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdmActionPerformed(evt);
            }
        });
        mnuAdmin.add(menuItemAdm);

        mnuPrinci.add(mnuAdmin);

        mnuEdit.setBackground(new java.awt.Color(59, 44, 133));
        mnuEdit.setText("Editar");

        mnuPerfil.setText("Perfil");
        mnuEdit.add(mnuPerfil);

        mnuPref.setText("Preferencias");
        mnuEdit.add(mnuPref);

        mnuPrinci.add(mnuEdit);

        setJMenuBar(mnuPrinci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminActionPerformed

    }//GEN-LAST:event_mnuAdminActionPerformed

    private void menuItemAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdmActionPerformed
        dialogAdmin da = new dialogAdmin(this, true, servidor, privK, pubK, pubKAjena);
        da.setVisible(true);
    }//GEN-LAST:event_menuItemAdmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItemAdm;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuPerfil;
    private javax.swing.JMenuItem mnuPref;
    private javax.swing.JMenuBar mnuPrinci;
    // End of variables declaration//GEN-END:variables

}
